name: Docker Hub build

on:
  push:
    branches:
      - develop
      - master
      - "release/*"
    tags:
      - "*" 

jobs:
  dockerhub:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@fix-dockerhub-action-tags
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
