name: Docker Hub build

on:
  push:
    branches:
      - "develop"
      - "master"
      - "release/*"
    tags:
      - "v*" # Triggered on tags that start with 'v'

jobs:
  dockerhub:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}